language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - ~/.composer/cache

matrix:
  include:
    - php: 5.6
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"
    - php: 7.1
      env: DEPENDENCIES="--prefer-lowest --prefer-stable"

before_install:
  - composer config github-oauth.github.com $GITHUB_TOKEN

install:
  - travis_retry composer update $DEPENDENCIES

script:
  - php vendor/bin/parallel-lint ./src ./tests
  - php vendor/bin/ecs check --config=vendor/shopsys/coding-standards/easy-coding-standard.yml --verbose ./src ./tests
  - php vendor/bin/phpunit tests
